# Generated by Django 5.2.8 on 2026-04-15 03:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_email_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('free', 'Free'), ('pro', 'Pro'), ('plus', 'Plus')], max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price_per_month', models.IntegerField(default=0, help_text='Price in cents')),
                ('max_scans_per_month', models.IntegerField(blank=True, help_text='null = unlimited', null=True)),
                ('max_concurrent_scans', models.IntegerField(default=1)),
                ('max_storage_gb', models.IntegerField(default=1)),
                ('api_rate_limit_per_minute', models.IntegerField(default=10)),
                ('support_level', models.CharField(choices=[('email', 'Email'), ('priority', 'Priority'), ('24/7', '24/7 Support')], default='email', max_length=20)),
                ('advanced_reporting', models.BooleanField(default=False)),
                ('custom_integrations', models.BooleanField(default=False)),
                ('dedicated_account_manager', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['price_per_month'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('upgrade', 'Upgrade'), ('downgrade', 'Downgrade'), ('renewal', 'Renewal'), ('cancellation', 'Cancellation'), ('suspension', 'Suspension'), ('reactivation', 'Reactivation')], max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_history', to=settings.AUTH_USER_MODEL)),
                ('new_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history_to', to='accounts.subscriptionplan')),
                ('old_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_from', to='accounts.subscriptionplan')),
            ],
            options={
                'verbose_name_plural': 'Subscription History',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scans_used_this_month', models.IntegerField(default=0)),
                ('current_storage_used_gb', models.FloatField(default=0.0)),
                ('api_calls_today', models.IntegerField(default=0)),
                ('usage_period_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_usage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Subscription Usage',
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('canceled', 'Canceled'), ('expired', 'Expired'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('current_period_start', models.DateTimeField()),
                ('current_period_end', models.DateTimeField()),
                ('subscription_id', models.CharField(blank=True, help_text='External payment processor subscription ID (Stripe, PayPal, etc.)', max_length=255, null=True, unique=True)),
                ('auto_renew', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.subscriptionplan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Subscriptions',
            },
        ),
    ]
