# Generated by Django 5.2.8 on 2026-04-15 07:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_subscription_plan_tier_capabilities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionusage',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='usersubscription',
            options={'verbose_name': 'User Subscription', 'verbose_name_plural': 'User Subscriptions'},
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='api_rate_limit_per_minute',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='display_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='max_concurrent_scans',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='max_scans_per_month',
            field=models.IntegerField(blank=True, help_text='null = unlimited monthly scans', null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='max_storage_gb',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='name',
            field=models.CharField(choices=[('free', 'Free'), ('pro', 'Pro'), ('plus', 'Plus')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='price_per_month',
            field=models.PositiveIntegerField(default=0, help_text='Price in cents'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='support_level',
            field=models.CharField(default='email', max_length=20),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='current_period_start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('canceled', 'Canceled'), ('expired', 'Expired'), ('past_due', 'Past Due')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='subscription_id',
            field=models.CharField(blank=True, help_text='External subscription id from Stripe/Razorpay', max_length=255, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='SubscriptionHistory',
        ),
        migrations.DeleteModel(
            name='SubscriptionUsage',
        ),
    ]
