# Generated by Django 5.2.8 on 2026-02-18 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconscan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portscanfinding',
            name='risk_tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
