# Generated by Django 5.2.8 on 2026-01-27 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reconscan', '0002_network_analysis_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='directoryfinding',
            new_name='reconscan_d_scan_id_40d871_idx',
            old_name='reconscan_d_scan_id_a7f3e5_idx',
        ),
        migrations.RenameIndex(
            model_name='directoryfinding',
            new_name='reconscan_d_issue_t_586c46_idx',
            old_name='reconscan_d_issue_t_5c8d2a_idx',
        ),
        migrations.RenameIndex(
            model_name='directoryfinding',
            new_name='reconscan_d_created_fee723_idx',
            old_name='reconscan_d_created_4a9b6c_idx',
        ),
        migrations.RenameIndex(
            model_name='portscanfinding',
            new_name='reconscan_p_scan_id_6c8e9d_idx',
            old_name='reconscan_p_scan_id_b6e8f9_idx',
        ),
        migrations.RenameIndex(
            model_name='portscanfinding',
            new_name='reconscan_p_created_418abb_idx',
            old_name='reconscan_p_created_3b6c4f_idx',
        ),
    ]
