# Generated by Django 5.2.8 on 2026-02-18 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reconscan', '0002_add_port_risk_fields'),
        ('reconscan', '0004_subdomain_enhanced_fields'),
    ]

    operations = [
    ]
