# Generated by Django 5.2.8 on 2026-02-18 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconscan', '0005_merge_20260218_0653'),
    ]

    operations = [
        migrations.AddField(
            model_name='portscanfinding',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
