# Generated by Django 5.2.8 on 2026-02-18 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconscan', '0006_portscanfinding_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=16),
        ),
    ]
