# Generated by Django 5.2.8 on 2026-03-06 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconscan', '0007_alter_scan_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='auth_cookies',
            field=models.JSONField(blank=True, default=dict, help_text='Authentication cookies for vulnerability testing (e.g., sessionid)'),
        ),
        migrations.AddField(
            model_name='scan',
            name='auth_headers',
            field=models.JSONField(blank=True, default=dict, help_text='Authentication headers for vulnerability testing (e.g., Authorization: Bearer token)'),
        ),
    ]
