# Generated by Django 5.2.8 on 2026-05-28 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconscan', '0008_scan_auth_cookies_scan_auth_headers'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='auth_type',
            field=models.CharField(blank=True, choices=[('none', 'No Auto-Login'), ('form', 'Form Login')], default='none', help_text='Optional auto-login mode for crawlers (e.g., form login for DVWA)', max_length=20),
        ),
        migrations.AddField(
            model_name='scan',
            name='login_url',
            field=models.URLField(blank=True, default='', help_text='Login page URL for form-based auto-login', max_length=500),
        ),
        migrations.AddField(
            model_name='scan',
            name='password',
            field=models.CharField(blank=True, default='', help_text='Password for form-based auto-login', max_length=255),
        ),
        migrations.AddField(
            model_name='scan',
            name='username',
            field=models.CharField(blank=True, default='', help_text='Username for form-based auto-login', max_length=255),
        ),
    ]
