# Generated by Django 5.2.8 on 2026-04-01 03:47

import kyc.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycsubmission',
            name='doc_back',
            field=models.ImageField(blank=True, null=True, storage=kyc.storage.KYCPrivateStorage(), upload_to='kyc/docs/'),
        ),
        migrations.AlterField(
            model_name='kycsubmission',
            name='doc_front',
            field=models.ImageField(storage=kyc.storage.KYCPrivateStorage(), upload_to='kyc/docs/'),
        ),
        migrations.AlterField(
            model_name='kycsubmission',
            name='selfie',
            field=models.ImageField(storage=kyc.storage.KYCPrivateStorage(), upload_to='kyc/selfies/'),
        ),
    ]
