# Generated by Django 5.2.8 on 2026-02-04 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vulnscan', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='vulnerabilityfinding',
            new_name='vulnscan_vu_scan_id_cec026_idx',
            old_name='vulnscan_vu_scan_id_5b1a7d_idx',
        ),
        migrations.RenameIndex(
            model_name='vulnerabilityfinding',
            new_name='vulnscan_vu_owasp_c_537fb5_idx',
            old_name='vulnscan_vu_owasp_c_85b3a0_idx',
        ),
        migrations.RenameIndex(
            model_name='vulnerabilityfinding',
            new_name='vulnscan_vu_created_b74453_idx',
            old_name='vulnscan_vu_created_0a6e5f_idx',
        ),
    ]
