# Generated by Django 5.2.8 on 2026-04-28 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reconscan', '0008_scan_auth_cookies_scan_auth_headers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('generating', 'Generating'), ('ready', 'Ready'), ('expired', 'Expired'), ('failed', 'Failed')], default='generating', max_length=20)),
                ('version', models.IntegerField(default=1)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ttl_minutes', models.IntegerField(default=1440)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('generation_errors', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('scan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='reconscan.scan')),
            ],
        ),
        migrations.CreateModel(
            name='ReportFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finding_type', models.CharField(choices=[('high_risk_port', 'High-Risk Port'), ('weak_tls', 'Weak TLS Configuration'), ('expired_cert', 'Expired Certificate'), ('sensitive_exposure', 'Sensitive File Exposure'), ('weak_http_headers', 'Missing Security Headers'), ('outdated_software', 'Outdated Software'), ('open_service', 'Open Service'), ('other', 'Other')], max_length=50)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('info', 'Informational')], max_length=20)),
                ('target_host', models.CharField(db_index=True, max_length=255)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('cvss_vector', models.CharField(blank=True, max_length=100)),
                ('cvss_score', models.FloatField(blank=True, null=True)),
                ('risk_score', models.FloatField(default=0.0)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('affected_items', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('custom_tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='reporting.report')),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_findings', to='reconscan.scan')),
            ],
        ),
        migrations.CreateModel(
            name='RemediationGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(default=1)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('affected_components', models.JSONField(default=list)),
                ('estimated_effort', models.CharField(choices=[('quick', '< 1 hour'), ('medium', '1-4 hours'), ('long', '> 4 hours')], default='medium', max_length=20)),
                ('references', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remediation_guides', to='reporting.reportfinding')),
            ],
            options={
                'ordering': ['priority'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('framework', models.CharField(choices=[('owasp_top10', 'OWASP Top 10'), ('owasp_api', 'OWASP API Top 10'), ('cwe', 'CWE (Common Weakness Enumeration)'), ('nist_csf', 'NIST Cybersecurity Framework'), ('pci_dss', 'PCI DSS'), ('hipaa', 'HIPAA'), ('gdpr', 'GDPR')], max_length=50)),
                ('identifier', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('link', models.URLField(blank=True)),
                ('finding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_mappings', to='reporting.reportfinding')),
            ],
        ),
        migrations.CreateModel(
            name='ScanComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comparison_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons_as_current', to='reconscan.scan')),
                ('previous_scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons_as_previous', to='reconscan.scan')),
            ],
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['created_by', 'created_at'], name='reporting_r_created_c78955_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['expires_at'], name='reporting_r_expires_3c9d9e_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['status'], name='reporting_r_status_b3f463_idx'),
        ),
        migrations.AddIndex(
            model_name='reportfinding',
            index=models.Index(fields=['report', 'severity'], name='reporting_r_report__2cbf9d_idx'),
        ),
        migrations.AddIndex(
            model_name='reportfinding',
            index=models.Index(fields=['target_host'], name='reporting_r_target__63280a_idx'),
        ),
        migrations.AddIndex(
            model_name='reportfinding',
            index=models.Index(fields=['finding_type'], name='reporting_r_finding_c99202_idx'),
        ),
        migrations.AddIndex(
            model_name='reportfinding',
            index=models.Index(fields=['is_active'], name='reporting_r_is_acti_12f0d6_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancemapping',
            index=models.Index(fields=['framework'], name='reporting_c_framewo_2ef674_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancemapping',
            index=models.Index(fields=['identifier'], name='reporting_c_identif_8aab35_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='compliancemapping',
            unique_together={('finding', 'framework', 'identifier')},
        ),
        migrations.AddIndex(
            model_name='scancomparison',
            index=models.Index(fields=['previous_scan', 'current_scan'], name='reporting_s_previou_930856_idx'),
        ),
        migrations.AddIndex(
            model_name='scancomparison',
            index=models.Index(fields=['created_at'], name='reporting_s_created_f85218_idx'),
        ),
    ]
